name = "worker-worktop" # TODO
main = "./src/index.ts"
compatibility_date = "2022-05-03"

cache_api_key = "https://worker-worktop.ptp-ai.workers.dev"

#
# NOTE: You will need to use `wrangler secret put JWT_SECRET <value>
# @see https://developers.cloudflare.com/workers/wrangler/commands/#secret
#
# [secrets]
# JWT_SECRET = "value"

[[kv_namespaces]]
binding = "DATABASE"
preview_id = "54657f7b0ceb4e958590eb925e5f95ec" # TODO
id = "54657f7b0ceb4e958590eb925e5f95ec" # TODO

